name: codexia
description: "Codexia is a simple app to discover, save, and borrow books youâ€™ll love."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  dio: ^5.9.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
